import React, { useState, useRef } from 'react';
import { Link } from 'react-router-dom';
import { 
  UploadCloud, 
  CheckCircle, 
  Shield, 
  FileText, 
  Search, 
  RefreshCw, 
  XCircle,
  ArrowLeft,
  CheckCircle2,
  Lock,
  ExternalLink,
  ShieldCheck,
  Check
} from 'lucide-react';
import { blockchainApi } from '../../services/blockchainApi';
import { Button } from '../../components/ui/Button';
import { CopyButton } from '../../components/ui/CopyButton';
import { formatDateTime } from '../../utils/dateFormat';

export default function VerifyAuditTrail() {
  const [dragActive, setDragActive] = useState<boolean>(false);
  const [file, setFile] = useState<File | null>(null);
  const [verifying, setVerifying] = useState<boolean>(false);
  const [error, setError] = useState<string>('');
  const [result, setResult] = useState<any>(null);
  
  const inputRef = useRef<HTMLInputElement>(null);

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const processVerification = async (selectedFile: File) => {
    if (!selectedFile.name.toLowerCase().endsWith('.pdf')) {
      setError('Only PDF files are accepted for verification.');
      setResult(null);
      return;
    }

    setVerifying(true);
    setError('');
    setResult(null);

    try {
      const res = await blockchainApi.verify(selectedFile);
      setResult(res);
    } catch (err: any) {
      setError(err.message || 'Verification failed. Document not found on the smart contract registry.');
    } finally {
      setVerifying(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const droppedFile = e.dataTransfer.files[0];
      setFile(droppedFile);
      processVerification(droppedFile);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();
    if (e.target.files && e.target.files[0]) {
      const chosenFile = e.target.files[0];
      setFile(chosenFile);
      processVerification(chosenFile);
    }
  };

  return (
    <div className="max-w-4xl mx-auto pt-6 sm:pt-8 pb-12 space-y-6 text-md-on-surface px-4 sm:px-0">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-md-outline/15">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-bold uppercase tracking-wider bg-md-primary/10 text-md-primary">
              Cryptographic Notarisation
            </span>
            <span className="text-xs text-md-on-surface-variant">Immutable Audit Trail</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-md-on-surface">
            Blockchain Document Verification
          </h1>
          <p className="text-xs sm:text-sm text-md-on-surface-variant mt-1">
            Verify the statutory award (Form H) or the payment receipt against its on-chain SHA-256 anchor — both milestones of a case are independently notarized.
          </p>
        </div>

        <Link
          to="/member"
          className="inline-flex items-center gap-1.5 text-xs sm:text-sm font-bold text-md-primary hover:underline self-start sm:self-center shrink-0"
        >
          <ArrowLeft size={16} />
          <span>Return to Dashboard</span>
        </Link>
      </div>

      {/* Info Banner */}
      <div className="p-4 sm:p-5 rounded-2xl bg-md-surface-container border border-md-outline/15 flex items-start gap-3.5 shadow-xs">
        <Shield size={22} className="text-md-primary shrink-0 mt-0.5" />
        <div className="text-xs sm:text-sm text-md-on-surface-variant leading-relaxed">
          <span className="font-bold text-md-on-surface">Zero-Knowledge Integrity Check: </span>
          Every official compensation voucher and settlement certificate generated by FCR-SCS is cryptographically hashed and published to the Ethereum blockchain ledger. Drag & drop your PDF file below to verify its on-chain validity.
        </div>
      </div>

      {/* Row 1: Upload Dropzone */}
      <div className="relative group w-full">
        <div 
          className={`relative w-full bg-md-surface-container border-2 border-dashed rounded-2xl p-8 sm:p-10 text-center transition-all duration-200 ease-md-bouncy flex flex-col items-center justify-center min-h-[220px] ${
            dragActive 
              ? 'border-md-primary bg-md-secondary-container/50' 
              : 'border-md-outline/30 hover:border-md-primary/60'
          }`}
          onDragEnter={handleDrag}
          onDragLeave={handleDrag}
          onDragOver={handleDrag}
          onDrop={handleDrop}
        >
          <input 
            ref={inputRef}
            type="file" 
            className="hidden" 
            accept=".pdf"
            onChange={handleChange}
          />
          
          {!file ? (
            <div 
              className="flex flex-col items-center cursor-pointer w-full" 
              onClick={() => inputRef.current?.click()}
            >
              <div className="w-16 h-16 bg-md-surface-container-low rounded-full flex items-center justify-center mb-4 group-hover:scale-105 transition-transform duration-200 shadow-sm text-md-primary">
                <UploadCloud size={34} />
              </div>
              <h3 className="text-base sm:text-lg font-bold text-md-on-surface mb-1">
                Upload Statutory or Settlement PDF
              </h3>
              <p className="text-xs sm:text-sm text-md-on-surface-variant mb-3 max-w-md">
                Drag &amp; drop your official certificate PDF here, or click to browse files
              </p>
              <span className="px-3.5 py-1 bg-md-surface-container-low rounded-full text-xs text-md-on-surface-variant font-semibold border border-md-outline/15">
                Official Form H Award &amp; Settlement Voucher (.PDF)
              </span>
            </div>
          ) : (
            <div className="flex flex-col items-center">
              <div className="w-16 h-16 bg-md-surface-container-low rounded-full flex items-center justify-center mb-4 text-md-primary shadow-sm">
                <FileText size={34} />
              </div>
              <h3 className="text-base font-bold text-md-on-surface mb-1 truncate w-full max-w-md">
                {file.name}
              </h3>
              <p className="text-xs text-md-on-surface-variant mb-4">
                {(file.size / 1024 / 1024).toFixed(2)} MB
              </p>
              
              {!verifying && (
                <Button 
                  variant="tonal"
                  onClick={(e) => { 
                    e.stopPropagation(); 
                    setFile(null); 
                    setResult(null); 
                    setError(''); 
                  }}
                >
                  <span>Verify Another File</span>
                </Button>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Row 2: Verification Details Result Panel */}
      <div className="bg-md-surface-container border border-md-outline/15 rounded-2xl p-6 sm:p-8 shadow-sm">
        {!result && !verifying && !error && (
          <div className="text-center py-10 opacity-75">
            <Search size={44} className="text-md-primary mx-auto mb-3 opacity-60" />
            <h4 className="text-base font-bold text-md-on-surface mb-1">
              Awaiting Document Submission
            </h4>
            <p className="text-xs sm:text-sm text-md-on-surface-variant max-w-sm mx-auto">
              Select or drop a statutory award or settlement receipt PDF above to begin instant cryptographic verification against the Ethereum ledger.
            </p>
          </div>
        )}

        {verifying && (
          <div className="text-center py-12 space-y-4">
            <RefreshCw size={44} className="text-md-primary animate-spin mx-auto" />
            <p className="text-sm sm:text-base font-bold text-md-on-surface">
              Computing SHA-256 Hash &amp; Querying Ethereum Blockchain...
            </p>
            <p className="text-xs text-md-on-surface-variant">
              Verifying cryptographic authenticity with smart contract registry.
            </p>
          </div>
        )}

        {error && (
          <div className="text-center py-8 space-y-3">
            <XCircle size={44} className="text-red-500 mx-auto" />
            <h4 className="text-base sm:text-lg font-bold text-red-600 dark:text-red-400">
              Verification Unsuccessful
            </h4>
            <p className="text-xs sm:text-sm text-md-on-surface-variant max-w-md mx-auto">
              {error}
            </p>
          </div>
        )}

        {result && (
          <div className="space-y-6">
            <div className="text-center pb-2">
              <div className="w-16 h-16 bg-md-surface-container-low rounded-full flex items-center justify-center mx-auto mb-3.5 shadow-sm">
                {result.verified ? (
                  <CheckCircle2 size={38} className="text-emerald-600 dark:text-emerald-400" />
                ) : result.status === 'Voided' ? (
                  <XCircle size={38} className="text-amber-500" />
                ) : (
                  <XCircle size={38} className="text-red-500" />
                )}
              </div>
              
              <h3 className={`text-xl sm:text-2xl font-bold ${result.verified ? 'text-emerald-700 dark:text-emerald-400' : result.status === 'Voided' ? 'text-amber-600' : 'text-red-600'}`}>
                {result.verified ? 'Cryptographically Verified on Ethereum' : result.status === 'Voided' ? 'Document Voided on Blockchain' : 'Certificate Altered / Unverified'}
              </h3>
              <p className="text-xs sm:text-sm text-md-on-surface-variant mt-1.5 font-medium">
                {result.message}
              </p>
            </div>
            
            {/* Full Details Container */}
            <div className="bg-md-surface-container-low rounded-2xl p-5 sm:p-7 text-left border border-md-outline/15 space-y-3.5 text-xs sm:text-sm">
              <div className="flex justify-between items-center pb-3 border-b border-md-outline/10">
                <span className="text-md-on-surface-variant font-semibold">Verification Status</span>
                <span className={`font-bold px-3 py-1 rounded-full text-xs ${
                  result.verified
                    ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border border-emerald-500/30'
                    : result.status === 'Voided'
                    ? 'bg-amber-500/10 text-amber-700 dark:text-amber-400 border border-amber-500/30'
                    : 'bg-red-500/10 text-red-700 dark:text-red-400 border border-red-500/30'
                }`}>
                  {result.status || (result.verified ? 'AUTHENTIC' : 'INVALID')}
                </span>
              </div>

              {result.milestone && (
                <div className="pb-3 border-b border-md-outline/10">
                  <div className="flex justify-between items-center">
                    <span className="text-md-on-surface-variant font-semibold">Milestone</span>
                    <span className="font-bold text-md-on-surface text-xs sm:text-sm">
                      {result.milestone === 'M1' ? 'Milestone 1 (M1) — Statutory Form H Award' : 'Milestone 2 (M2) — Payment Settlement'}
                    </span>
                  </div>
                  <p className="text-xs text-md-on-surface-variant mt-1">
                    {result.milestone === 'M1'
                      ? 'Government Form H compensation offer accepted by landowner, anchored prior to disbursement.'
                      : 'Official payment receipt & clearance record after RENTAS interbank settlement.'}
                  </p>
                </div>
              )}

              {result.caseId && (
                <div className="flex justify-between items-center pb-3 border-b border-md-outline/10">
                  <span className="text-md-on-surface-variant font-semibold">Case ID</span>
                  <span className="font-mono font-bold text-md-on-surface text-xs sm:text-sm">{result.caseId}</span>
                </div>
              )}

              {result.onChainKey && (
                <div className="flex justify-between items-center pb-3 border-b border-md-outline/10">
                  <span className="text-md-on-surface-variant font-semibold">On-Chain Ledger Key</span>
                  <span className="font-mono font-bold text-md-on-surface text-xs sm:text-sm">{result.onChainKey}</span>
                </div>
              )}

              {/* SHA-256 Hash Comparison */}
              {result.localHash && (
                <div className="pt-1 pb-2 border-b border-md-outline/10 space-y-2">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1.5">
                    <span className="text-md-on-surface-variant font-semibold">Uploaded File SHA-256</span>
                    <div className="flex items-center gap-1.5">
                      <span className="font-mono text-xs text-md-on-surface truncate max-w-[220px] sm:max-w-md">
                        {result.localHash}
                      </span>
                      <CopyButton value={result.localHash} title="Copy file hash" size="sm" />
                    </div>
                  </div>
                  {result.onChainHash && (
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1.5">
                      <span className="text-md-on-surface-variant font-semibold">On-Chain Registered Hash</span>
                      <div className="flex items-center gap-1.5">
                        <span className="font-mono text-xs text-emerald-700 dark:text-emerald-400 truncate max-w-[220px] sm:max-w-md font-semibold">
                          {result.onChainHash}
                        </span>
                        <span className="inline-flex items-center text-xs text-emerald-700 dark:text-emerald-400 font-bold ml-1">
                          <Check size={12} className="mr-0.5" /> {result.localHash.toLowerCase() === result.onChainHash.toLowerCase() ? 'Direct Match' : 'Verified Anchor'}
                        </span>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* Transaction Hash with Etherscan Link */}
              {result.transactionHash && (
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1.5 pb-3 border-b border-md-outline/10">
                  <span className="text-md-on-surface-variant font-semibold">Transaction Hash</span>
                  <div className="flex items-center gap-2">
                    <a
                      href={result.etherscanUrl || `https://sepolia.etherscan.io/tx/${result.transactionHash}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-mono text-xs sm:text-sm text-md-primary hover:underline inline-flex items-center gap-1 font-semibold"
                      title="View transaction on Sepolia Etherscan"
                    >
                      <span className="truncate max-w-[200px] sm:max-w-none">{result.transactionHash}</span>
                      <ExternalLink size={13} className="shrink-0" />
                    </a>
                    <CopyButton value={result.transactionHash} title="Copy transaction hash" size="sm" />
                  </div>
                </div>
              )}

              {/* Contract Address with Etherscan Link */}
              {result.contractAddress && (
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1.5 pb-3 border-b border-md-outline/10">
                  <span className="text-md-on-surface-variant font-semibold">Smart Contract</span>
                  <div className="flex items-center gap-2">
                    <a
                      href={result.contractUrl || `https://sepolia.etherscan.io/address/${result.contractAddress}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-mono text-xs sm:text-sm text-md-primary hover:underline inline-flex items-center gap-1 font-semibold"
                      title="View contract registry on Sepolia Etherscan"
                    >
                      <span className="truncate max-w-[200px] sm:max-w-none">{result.contractAddress}</span>
                      <ExternalLink size={13} className="shrink-0" />
                    </a>
                    <CopyButton value={result.contractAddress} title="Copy contract address" size="sm" />
                  </div>
                </div>
              )}

              {/* Network & Timestamp */}
              <div className="flex justify-between items-center">
                <span className="text-md-on-surface-variant font-semibold">Network</span>
                <span className="text-xs sm:text-sm text-md-on-surface font-medium">
                  {result.network || 'Sepolia Testnet (Chain ID 11155111)'}
                </span>
              </div>

              {result.timestamp && (
                <div className="flex justify-between items-center">
                  <span className="text-md-on-surface-variant font-semibold">On-Chain Timestamp</span>
                  <span className="font-mono text-md-on-surface text-xs sm:text-sm font-medium">
                    {formatDateTime(result.timestamp * 1000)}
                  </span>
                </div>
              )}

              {result.voidReason && (
                <div className="pt-3 border-t border-red-500/20 text-red-600">
                  <div className="flex justify-between items-start">
                    <span className="font-bold">Void Reason</span>
                    <span className="text-right max-w-sm font-medium">{result.voidReason}</span>
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
