/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FCRSCSLedgerInterface extends Interface {
  getFunction(
    nameOrSignature: "getRecord" | "owner" | "publishRecord" | "voidRecord"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RecordPublished" | "RecordVoided"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getRecord", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publishRecord",
    values: [string, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "voidRecord",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voidRecord", data: BytesLike): Result;
}

export namespace RecordPublishedEvent {
  export type InputTuple = [
    caseId: string,
    documentHashes: BytesLike[],
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    caseId: string,
    documentHashes: string[],
    timestamp: bigint
  ];
  export interface OutputObject {
    caseId: string;
    documentHashes: string[];
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordVoidedEvent {
  export type InputTuple = [
    caseId: string,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [caseId: string, reason: string, timestamp: bigint];
  export interface OutputObject {
    caseId: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FCRSCSLedger extends BaseContract {
  connect(runner?: ContractRunner | null): FCRSCSLedger;
  waitForDeployment(): Promise<this>;

  interface: FCRSCSLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRecord: TypedContractMethod<
    [caseId: string],
    [
      [string[], bigint, boolean, string, bigint] & {
        documentHashes: string[];
        publishedAt: bigint;
        isVoided: boolean;
        voidReason: string;
        voidedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  publishRecord: TypedContractMethod<
    [caseId: string, documentHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  voidRecord: TypedContractMethod<
    [caseId: string, reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [caseId: string],
    [
      [string[], bigint, boolean, string, bigint] & {
        documentHashes: string[];
        publishedAt: bigint;
        isVoided: boolean;
        voidReason: string;
        voidedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publishRecord"
  ): TypedContractMethod<
    [caseId: string, documentHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voidRecord"
  ): TypedContractMethod<
    [caseId: string, reason: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RecordPublished"
  ): TypedContractEvent<
    RecordPublishedEvent.InputTuple,
    RecordPublishedEvent.OutputTuple,
    RecordPublishedEvent.OutputObject
  >;
  getEvent(
    key: "RecordVoided"
  ): TypedContractEvent<
    RecordVoidedEvent.InputTuple,
    RecordVoidedEvent.OutputTuple,
    RecordVoidedEvent.OutputObject
  >;

  filters: {
    "RecordPublished(string,bytes32[],uint256)": TypedContractEvent<
      RecordPublishedEvent.InputTuple,
      RecordPublishedEvent.OutputTuple,
      RecordPublishedEvent.OutputObject
    >;
    RecordPublished: TypedContractEvent<
      RecordPublishedEvent.InputTuple,
      RecordPublishedEvent.OutputTuple,
      RecordPublishedEvent.OutputObject
    >;

    "RecordVoided(string,string,uint256)": TypedContractEvent<
      RecordVoidedEvent.InputTuple,
      RecordVoidedEvent.OutputTuple,
      RecordVoidedEvent.OutputObject
    >;
    RecordVoided: TypedContractEvent<
      RecordVoidedEvent.InputTuple,
      RecordVoidedEvent.OutputTuple,
      RecordVoidedEvent.OutputObject
    >;
  };
}
