/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FCRSCSLedger } from "./FCRSCSLedger";
export * as factories from "./factories";
export { FCRSCSLedger__factory } from "./factories/FCRSCSLedger__factory";
