/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CompensationLedger } from "./CompensationLedger";
export * as factories from "./factories";
export { CompensationLedger__factory } from "./factories/CompensationLedger__factory";
