import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { FileText, Loader2, Plus, CheckCircle, Clock, XCircle } from "lucide-react";
import { CaseSelectionModal } from "../LandAcquisition/CaseSelectionModal";
import { Pagination } from "../../components/ui/Pagination";
import { Button } from "../../components/ui/Button";
import { Select } from "../../components/ui/Select";
import { SearchInput } from "../../components/ui/SearchInput";
import { CopyButton } from "../../components/ui/CopyButton";
import { PageHeader } from "../../components/ui/PageHeader";
import { useRole } from "../../hooks/useRole";
import { useNotification } from "../../components/ui/NotificationSystem";
import { formatCurrencyRM } from "../../utils/currency";
import type { CompensationReportItem } from "./types/compensation.types";
import { useCompensationReports } from "./hooks/useCompensationReports";
import {
  COMPENSATION_STATUS_LABEL_MAP as statusLabelMap,
  COMPENSATION_STATUS_OPTIONS as STATUS_OPTIONS,
  useTableSort,
} from "../../constants";
import "../../index.css";
import "./compensation.css";

export const CompensationDashboard: React.FC = () => {
  const navigate = useNavigate();
  const { userId, role, isAdmin, isOfficer, isGovAdmin, canCreateCompensationReport } = useRole();
  const { notify } = useNotification();

  const { allReports, loading } = useCompensationReports({
    isAdmin,
    isOfficer,
    userId,
    role,
  });

  const [reports, setReports] = useState<CompensationReportItem[]>([]);
  const [totalCount, setTotalCount] = useState<number>(0);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [isCaseModalOpen, setIsCaseModalOpen] = useState(false);
  const itemsPerPage = 10;

  const { sortKey, sortDirection, handleSort, renderSortIcon, sortItems } =
    useTableSort<keyof CompensationReportItem>();

  // Filter data based on search and status
  const filteredReports = React.useMemo(() => {
    let list = allReports;

    if (searchTerm) {
      const term = searchTerm.toLowerCase();
      list = list.filter(
        (r) =>
          r.caseId.toLowerCase().includes(term) ||
          r.caseTitle.toLowerCase().includes(term) ||
          r.owner.toLowerCase().includes(term) ||
          r.id.toLowerCase().includes(term)
      );
    }

    if (statusFilter) {
      const expectedLabel = statusLabelMap[statusFilter] || statusFilter;
      list = list.filter((r) => r.status === expectedLabel || r.status === statusFilter);
    }

    return list;
  }, [allReports, searchTerm, statusFilter]);

  // Sort filtered reports
  const sortedReports = React.useMemo(() => {
    return sortItems(filteredReports, {
      generatedDate: (r) => (r.generatedDate && r.generatedDate !== "—" ? new Date(r.generatedDate).getTime() : 0),
    });
  }, [filteredReports, sortKey, sortDirection, sortItems]);

  // Paginate sorted data
  useEffect(() => {
    setTotalCount(sortedReports.length);
    const startIndex = (currentPage - 1) * itemsPerPage;
    setReports(sortedReports.slice(startIndex, startIndex + itemsPerPage));
  }, [sortedReports, currentPage, itemsPerPage]);

  const handleView = (reportId: string) => {
    navigate("/admin/compensation/report/review", { state: { reportId } });
  };

  const handleCreateReport = () => {
    if (isGovAdmin) {
      notify({
        type: "error",
        title: "Access Denied",
        message: "Government Administrators cannot create compensation reports. Reports must be generated by Government Officers.",
      });
      return;
    }
    if (!canCreateCompensationReport) {
      notify({
        type: "error",
        title: "Access Denied",
        message: "Only Government Officers can create compensation reports.",
      });
      return;
    }
    setIsCaseModalOpen(true);
  };

  const handleSelectCaseFromModal = (caseId: string) => {
    setIsCaseModalOpen(false);
    navigate("/admin/compensation/report/create", { state: { caseId } });
  };

  // Metrics dynamically derived directly from filtered data
  const stats = [
    { label: "Total Reports", value: filteredReports.length, icon: <FileText size={16} className="inline mr-1" /> },
    {
      label: "Approved",
      value: filteredReports.filter((r) => r.status === "Approved").length,
      icon: <CheckCircle size={16} className="inline mr-1" />,
    },
    {
      label: "Pending Approval",
      value: filteredReports.filter((r) => r.status === "Pending Approval").length,
      icon: <Clock size={16} className="inline mr-1" />,
    },
    {
      label: "Rejected",
      value: filteredReports.filter((r) => r.status === "Rejected").length,
      icon: <XCircle size={16} className="inline mr-1" />,
    },
  ];

  return (
    <>
      {/* Case Selection Modal */}
      <CaseSelectionModal
        isOpen={isCaseModalOpen}
        onClose={() => setIsCaseModalOpen(false)}
        onSelectCase={handleSelectCaseFromModal}
        allowedStatuses={["VALUATION_APPROVED", "COMPENSATION_REJECTED"]}
        title="Select Case for Compensation Report"
        subtitle="Choose a case in Valuation Approved or Compensation Rejected status to create a report."
        emptyMessage="No cases currently in Valuation Approved or Compensation Rejected status."
      />

      <div className="compensation-dashboard">
        <PageHeader
          title="Compensation Report Dashboard"
          subtitle={
            isAdmin
              ? "Review and manage all compensation calculation reports across the system"
              : isOfficer
              ? "Review and generate compensation calculation reports for cases created by your account"
              : "Review and manage compensation calculation reports"
          }
        />

        <div className="stats-grid">
          {stats.map((s, i) => (
            <div className="stat-card" key={i}>
              <span className="stat-icon">{s.icon}</span>
              <div className="stat-label">{s.label}</div>
              <div className="stat-number">{s.value}</div>
            </div>
          ))}
        </div>

        <div className="filter-bar flex items-center justify-between gap-4">
          <div className="search-wrap min-w-[280px]">
            <SearchInput
              placeholder="Search by case title or report ID..."
              value={searchTerm}
              onChange={(e) => {
                setSearchTerm(e.target.value);
                setCurrentPage(1);
              }}
            />
          </div>
          <div className="filter-group">
            <Select
              label="Status"
              value={statusFilter}
              options={STATUS_OPTIONS}
              onChange={(val) => {
                setStatusFilter(val);
                setCurrentPage(1);
              }}
              placeholder="All Status"
            />
          </div>
        </div>

        {/* Action Bar */}
        <div className="action-bar">
          <div className="left">
            <span className="count">{totalCount}</span> reports found
            <span style={{ opacity: 0.4, margin: "0 4px" }}>·</span>
            <span style={{ fontSize: "13px" }}>
              Showing {reports.length > 0 ? (currentPage - 1) * itemsPerPage + 1 : 0}–
              {Math.min(currentPage * itemsPerPage, totalCount)} of {totalCount}
            </span>
          </div>

          {canCreateCompensationReport && (
            <div className="right">
              <Button variant="filled" onClick={handleCreateReport}>
                <Plus size={16} /> New Report
              </Button>
            </div>
          )}
        </div>

        <div className="table-wrap">
          <div className="table-scroll md-scroll-thin">
            <table className="w-full table-fixed">
              <thead>
                <tr>
                  <th style={{ width: "18%" }} onClick={() => handleSort("id")} className="cursor-pointer select-none">
                    Report ID {renderSortIcon("id")}
                  </th>
                  <th style={{ width: "28%" }} onClick={() => handleSort("caseTitle")} className="cursor-pointer select-none">
                    Case Title {renderSortIcon("caseTitle")}
                  </th>
                  <th style={{ width: "18%" }} onClick={() => handleSort("owner")} className="cursor-pointer select-none">
                    Land Owner {renderSortIcon("owner")}
                  </th>
                  <th style={{ width: "14%" }} onClick={() => handleSort("totalAmount")} className="cursor-pointer select-none">
                    Total Amount {renderSortIcon("totalAmount")}
                  </th>
                  <th style={{ width: "12%" }} onClick={() => handleSort("status")} className="cursor-pointer select-none">
                    Status {renderSortIcon("status")}
                  </th>
                  <th style={{ width: "10%" }} onClick={() => handleSort("generatedDate")} className="cursor-pointer select-none">
                    Date {renderSortIcon("generatedDate")}
                  </th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr>
                    <td colSpan={6} style={{ textAlign: "center", padding: "32px", color: "var(--md-on-surface-variant)" }}>
                      <Loader2 size={24} className="inline animate-spin mr-2" /> Loading reports from backend...
                    </td>
                  </tr>
                ) : reports.length === 0 ? (
                  <tr>
                    <td colSpan={6} style={{ textAlign: "center", padding: "32px", color: "var(--md-on-surface-variant)", opacity: 0.6 }}>
                      No compensation reports found in database.
                    </td>
                  </tr>
                ) : (
                  reports.map((r) => (
                    <tr
                      key={r.id}
                      onClick={() => handleView(r.id)}
                      className="cursor-pointer hover:bg-md-primary/5 transition-colors"
                    >
                      <td>
                        <div className="flex items-center gap-1.5 min-w-0" onClick={(e) => e.stopPropagation()}>
                          <span className="case-id font-mono text-xs truncate block">{r.id}</span>
                          <CopyButton value={r.id} />
                        </div>
                      </td>
                      <td title={r.caseTitle}>
                        <span className="meta-text line-clamp-2 leading-snug block">{r.caseTitle}</span>
                      </td>
                      <td title={r.owner}>
                        <span className="meta-text line-clamp-2 leading-snug block">{r.owner}</span>
                      </td>
                      <td title={formatCurrencyRM(r.totalAmount)}>
                        <span className="meta-text line-clamp-2 leading-snug block">{formatCurrencyRM(r.totalAmount)}</span>
                      </td>
                      <td>
                        <span className={`status-badge ${r.statusClass}`}>
                          <span className="dot"></span> {r.status}
                        </span>
                      </td>
                      <td>
                        <span className="meta-text text-xs whitespace-nowrap">{r.generatedDate}</span>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>

          <Pagination
            currentPage={currentPage}
            totalPages={Math.max(1, Math.ceil(totalCount / itemsPerPage))}
            totalCount={totalCount}
            pageSize={itemsPerPage}
            onPageChange={setCurrentPage}
            itemLabel="reports"
          />
        </div>

        <div
          style={{
            marginTop: "24px",
            fontSize: "13px",
            color: "var(--md-on-surface-variant)",
            opacity: 0.6,
            textAlign: "center",
            borderTop: "1px solid rgba(121,116,126,0.08)",
            paddingTop: "18px",
          }}
        >
          FCR-SCS · Compensation Report Module · Connected to Business Logic Backend
        </div>
      </div>
    </>
  );
};

export const CompensationReportList = CompensationDashboard;
export default CompensationDashboard;
